"""
AI image analysis service.

This module is the single entry point for all AI-driven observation analysis.
Right now it routes to a rule-based mock when AI is disabled or credentials
are missing. When you are ready to connect Azure OpenAI, change only the
routing logic at the bottom of analyze_observation_image() — the rest of the
app (routes, models, templates) does not need to change.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from app.config import settings


@dataclass
class AIAnalysisResult:
    """Structured result returned by any analysis provider."""

    damage_tags: list[str]
    severity: int              # 1–5
    confidence: int            # 0–100
    summary: str
    recommended_action: str
    provider: str              # e.g. "mock", "azure_openai"
    raw_response: str | None = field(default=None)


# ── Mock / rule-based fallback ────────────────────────────────────────────────

def _mock_analyze(image_path: str, notes: str | None) -> AIAnalysisResult:
    """
    Returns a deterministic placeholder result based on the presence of an
    image file and any keywords found in the observer's notes.

    This is intentionally simple — it is only here to make the UI and database
    workflow functional before real AI is connected.
    """
    detected_tags: list[str] = []
    notes_lower = (notes or "").lower()

    # Keyword scan of the human notes — stands in for visual detection
    keyword_map = {
        "crack": "crack",
        "graffiti": "graffiti",
        "water": "water",
        "damp": "water",
        "flood": "water",
        "erosion": "erosion",
        "erode": "erosion",
        "vegetation": "vegetation",
        "plant": "vegetation",
        "moss": "vegetation",
        "stain": "staining",
        "staining": "staining",
        "discolour": "staining",
    }
    for keyword, tag in keyword_map.items():
        if keyword in notes_lower and tag not in detected_tags:
            detected_tags.append(tag)

    image_present = image_path and Path(image_path).exists()
    if not image_present and not detected_tags:
        detected_tags = ["staining"]  # minimal default so the result is never empty

    severity = min(5, max(1, len(detected_tags) + 1))
    confidence = 40 if detected_tags else 20  # low confidence — this is mock data

    summary_parts = []
    if not image_present:
        summary_parts.append("No image was available for visual analysis.")
    if detected_tags:
        summary_parts.append(
            f"Possible damage indicators detected from notes: {', '.join(detected_tags)}."
        )
    else:
        summary_parts.append("No specific damage indicators found in the observer notes.")
    summary_parts.append(
        "NOTE: This result is generated by a rule-based mock. "
        "Connect Azure OpenAI Vision to enable real image analysis."
    )

    return AIAnalysisResult(
        damage_tags=detected_tags,
        severity=severity,
        confidence=confidence,
        summary=" ".join(summary_parts),
        recommended_action=(
            "Schedule an in-person inspection to verify these findings."
            if detected_tags
            else "No immediate action required. Continue routine monitoring."
        ),
        provider="mock",
        raw_response=None,
    )


# ── Public entry point ────────────────────────────────────────────────────────

def analyze_observation_image(
    image_path: str,
    notes: str | None = None,
) -> AIAnalysisResult:
    """
    Analyse an observation image and return an AIAnalysisResult.

    Routing logic:
      1. If AI_ANALYSIS_ENABLED=false  → use mock (always safe, no API needed).
      2. If credentials are missing    → use mock (fail-safe).
      3. If AI_ANALYSIS_ENABLED=true and credentials present → call Azure OpenAI.

    To add a new provider later, import it here and add a branch below.
    """

    if not settings.ai_analysis_enabled:
        return _mock_analyze(image_path, notes)

    if not settings.azure_credentials_present:
        # Credentials not configured — fall back gracefully instead of crashing.
        result = _mock_analyze(image_path, notes)
        result.summary = (
            "[AI_ANALYSIS_ENABLED=true but Azure credentials are missing. "
            "Falling back to mock.] " + result.summary
        )
        return result

    # TODO: Route to the real Azure OpenAI provider when credentials are present.
    #
    # from app.services.providers.azure_openai_provider import AzureOpenAIImageAnalyzer
    # analyzer = AzureOpenAIImageAnalyzer()
    # return analyzer.analyze(image_path, notes)
    #
    # Remove this placeholder once the provider is implemented:
    raise NotImplementedError(
        "Azure OpenAI provider is not yet implemented. "
        "See app/services/providers/azure_openai_provider.py"
    )
