#!/usr/bin/env python3
"""Build a hash/dimension audit manifest for the private research corpus."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parents[1]
CORPUS_DIR = REPO_ROOT / "research" / "corpus"
DEFAULT_MANIFEST = CORPUS_DIR / "manifest.json"
DEFAULT_REPORT = CORPUS_DIR / "audit_report.md"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}
ROLES = ("WIDE", "MEDIUM", "CLOSE")


class CorpusAuditError(RuntimeError):
    pass


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _role_from_path(path: Path) -> str:
    tokens = [
        token.lower()
        for part in path.with_suffix("").parts
        for token in part.replace("-", "_").split("_")
    ]
    for role in ROLES:
        if role.lower() in tokens:
            return role
    raise CorpusAuditError(
        f"Cannot infer capture role from path '{path}'. "
        "Use wide, medium, or close in the filename or folder name."
    )


def _asset_group_from_path(relative_path: Path) -> str:
    if relative_path.parent == Path("."):
        stem = relative_path.stem.lower()
        for suffix in ("_wide", "_medium", "_close", "-wide", "-medium", "-close"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
        return stem or "ungrouped"
    return relative_path.parent.as_posix()


def _site_label_from_path(relative_path: Path) -> str:
    if len(relative_path.parts) >= 2:
        return relative_path.parts[0]
    return "unlabelled"


def _photo_id(relative_path: str) -> str:
    return "PHOTO-" + hashlib.sha256(relative_path.encode("utf-8")).hexdigest()[:12]


def _load_previous(path: Path | None) -> dict[str, dict[str, Any]]:
    if not path or not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {
        photo["relative_path"]: photo
        for photo in payload.get("photos", [])
        if isinstance(photo, dict) and photo.get("relative_path")
    }


def _image_files(photo_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in photo_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
    )


def _build_photo_record(
    *,
    path: Path,
    photo_dir: Path,
    previous: dict[str, dict[str, Any]],
    default_privacy_status: str,
    default_cultural_status: str,
) -> dict[str, Any]:
    relative_path = path.relative_to(photo_dir).as_posix()
    previous_record = previous.get(relative_path, {})
    with Image.open(path) as image:
        width, height = image.size
    return {
        "photo_id": previous_record.get("photo_id") or _photo_id(relative_path),
        "sha256": _sha256(path),
        "relative_path": relative_path,
        "width": width,
        "height": height,
        "capture_role": previous_record.get("capture_role") or _role_from_path(Path(relative_path)),
        "asset_group_id": previous_record.get("asset_group_id")
        or _asset_group_from_path(Path(relative_path)),
        "site_label": previous_record.get("site_label") or _site_label_from_path(Path(relative_path)),
        "privacy_status": previous_record.get("privacy_status", default_privacy_status),
        "cultural_sensitivity_status": previous_record.get(
            "cultural_sensitivity_status",
            default_cultural_status,
        ),
        "provenance_note": previous_record.get(
            "provenance_note",
            "Generated by corpus audit; clearance requires human review.",
        ),
    }


def _duplicates(photos: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_hash: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for photo in photos:
        by_hash[photo["sha256"]].append(photo)
    return [
        {
            "sha256": sha256,
            "photo_ids": [photo["photo_id"] for photo in grouped],
            "relative_paths": [photo["relative_path"] for photo in grouped],
        }
        for sha256, grouped in sorted(by_hash.items())
        if len(grouped) > 1
    ]


def _summary(photos: list[dict[str, Any]]) -> dict[str, Any]:
    counts_by_role = Counter(photo["capture_role"] for photo in photos)
    counts_by_asset = Counter(photo["asset_group_id"] for photo in photos)
    roles_by_asset: dict[str, set[str]] = defaultdict(set)
    for photo in photos:
        roles_by_asset[photo["asset_group_id"]].add(photo["capture_role"])
    complete_groups = [
        group_id
        for group_id, roles in roles_by_asset.items()
        if all(role in roles for role in ROLES)
    ]
    candidate_groups = [
        group_id
        for group_id, roles in roles_by_asset.items()
        if group_id not in complete_groups and roles
    ]
    excluded = [
        photo
        for photo in photos
        if photo["privacy_status"] != "cleared"
        or photo["cultural_sensitivity_status"] != "cleared"
    ]
    return {
        "total_photos": len(photos),
        "counts_by_role": {role: counts_by_role.get(role, 0) for role in ROLES},
        "counts_by_asset_group": dict(sorted(counts_by_asset.items())),
        "complete_asset_groups": len(complete_groups),
        "complete_asset_group_ids": sorted(complete_groups),
        "candidate_groups_needing_validation": len(candidate_groups),
        "candidate_group_ids": sorted(candidate_groups),
        "excluded_privacy_or_sensitive_items": len(excluded),
    }


def build_manifest(
    *,
    photo_dir: Path,
    previous_manifest: Path | None,
    default_privacy_status: str = "needs_review",
    default_cultural_status: str = "needs_review",
) -> dict[str, Any]:
    if not photo_dir.exists() or not photo_dir.is_dir():
        raise CorpusAuditError(f"Photo directory not found: {photo_dir}")
    previous = _load_previous(previous_manifest)
    photos = [
        _build_photo_record(
            path=path,
            photo_dir=photo_dir,
            previous=previous,
            default_privacy_status=default_privacy_status,
            default_cultural_status=default_cultural_status,
        )
        for path in _image_files(photo_dir)
    ]
    current_paths = {photo["relative_path"] for photo in photos}
    missing = [
        previous_record
        for relative_path, previous_record in sorted(previous.items())
        if relative_path not in current_paths
    ]
    return {
        "schema_version": "1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_root": str(photo_dir),
        "photos": photos,
        "duplicates": _duplicates(photos),
        "missing_files": missing,
        "summary": _summary(photos),
    }


def write_audit_report(manifest: dict[str, Any], path: Path) -> None:
    summary = manifest["summary"]
    duplicate_count = sum(len(group["photo_ids"]) for group in manifest.get("duplicates", []))
    lines = [
        "# Corpus Audit Report",
        "",
        f"Generated at: `{manifest['generated_at']}`",
        f"Source root: `{manifest['source_root']}`",
        "",
        "## Summary",
        "",
        f"- Total photos: {summary['total_photos']}",
        f"- Complete WIDE+MEDIUM+CLOSE asset groups: {summary['complete_asset_groups']}",
        f"- Candidate groups needing validation: {summary['candidate_groups_needing_validation']}",
        f"- Excluded privacy/sensitive items: {summary['excluded_privacy_or_sensitive_items']}",
        f"- Duplicate photo records by hash: {duplicate_count}",
        f"- Missing files from previous manifest: {len(manifest.get('missing_files', []))}",
        "",
        "## Counts by Role",
        "",
    ]
    for role, count in summary["counts_by_role"].items():
        lines.append(f"- {role}: {count}")
    lines.extend(["", "## Counts by Asset Group", ""])
    for group_id, count in summary["counts_by_asset_group"].items():
        lines.append(f"- {group_id}: {count}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("photo_dir", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--previous-manifest", type=Path)
    parser.add_argument(
        "--default-privacy-status",
        choices=("cleared", "needs_review", "excluded"),
        default="needs_review",
    )
    parser.add_argument(
        "--default-cultural-sensitivity-status",
        choices=("cleared", "needs_review", "sensitive", "excluded"),
        default="needs_review",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    previous_manifest = args.previous_manifest
    if previous_manifest is None and args.output.exists():
        previous_manifest = args.output
    try:
        manifest = build_manifest(
            photo_dir=args.photo_dir,
            previous_manifest=previous_manifest,
            default_privacy_status=args.default_privacy_status,
            default_cultural_status=args.default_cultural_sensitivity_status,
        )
    except CorpusAuditError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    write_audit_report(manifest, args.report)
    print(json.dumps(manifest["summary"], indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
